name: test-cli

on:
  push: 
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go 
        uses: actions/checkout@v2 
        with: 
          go-version: '1.17'
      - name: Install dependencies 
        run: |
          go version
          go install -v ./...
          
      - name: Build Binary file 
        run: |
          cd ./cmd/net-cli 
          go build -o netcli
      - name: Run Tests 
        run: |
          go test -v ./...